upload-doc = true
disable-publish = true
pre-release-commit-message = "Release v{{version}}"
tag-message = "{{crate_name}} version {{version}}"
no-dev-version = true
pre-release-hook = ["cargo", "make", "pre-release"]
